<?php
return [
    "en_US" => ["label" => "English (United States)", "countryCode" => "us"],
    "gu" => ["label" => "ગુજરાતી", "countryCode" => "in"],
    "hi_IN" => ["label" => "हिन्दी", "countryCode" => "in"],
    "af" => ["label" => "Afrikaans", "countryCode" => "za"],
    "am" => ["label" => "አማርኛ", "countryCode" => "et"],
    "arg" => ["label" => "Aragonés", "countryCode" => "es"],
    "ar" => ["label" => "العربية", "countryCode" => "sa"],
    "ary" => ["label" => "العربية المغربية", "countryCode" => "ma"],
    "as" => ["label" => "অসমীয়া", "countryCode" => "in"],
    "azb" => ["label" => "گؤنئی آذربایجان", "countryCode" => "az"],
    "az" => ["label" => "Azərbaycan dili", "countryCode" => "az"],
    "bel" => ["label" => "Беларуская мова", "countryCode" => "by"],
    "bg_BG" => ["label" => "Български", "countryCode" => "bg"],
    "bn_BD" => ["label" => "বাংলা", "countryCode" => "bd"],
    "bo" => ["label" => "བོད་ཡིག", "countryCode" => "cn"],
    "bs_BA" => ["label" => "Bosanski", "countryCode" => "ba"],
    "ca" => ["label" => "Català", "countryCode" => "es"],
    "ceb" => ["label" => "Cebuano", "countryCode" => "ph"],
    "cs_CZ" => ["label" => "Čeština", "countryCode" => "cz"],
    "cy" => ["label" => "Cymraeg", "countryCode" => "gb"],
    "da_DK" => ["label" => "Dansk", "countryCode" => "dk"],
    "de_CH" => ["label" => "Deutsch (Schweiz)", "countryCode" => "ch"],
    "de_AT" => ["label" => "Deutsch (Österreich)", "countryCode" => "at"],
    "de_DE" => ["label" => "Deutsch", "countryCode" => "de"],
    "de_DE_formal" => ["label" => "Deutsch (Sie)", "countryCode" => "de"],
    "de_CH_informal" => ["label" => "Deutsch (Schweiz, Du)", "countryCode" => "ch"],
    "dsb" => ["label" => "Dolnoserbšćina", "countryCode" => "de"],
    "dzo" => ["label" => "རྫོང་ཁ", "countryCode" => "bt"],
    "el" => ["label" => "Ελληνικά", "countryCode" => "gr"],
    "en_ZA" => ["label" => "English (South Africa)", "countryCode" => "za"],
    "en_AU" => ["label" => "English (Australia)", "countryCode" => "au"],
    "en_NZ" => ["label" => "English (New Zealand)", "countryCode" => "nz"],
    "en_GB" => ["label" => "English (UK)", "countryCode" => "gb"],
    "en_CA" => ["label" => "English (Canada)", "countryCode" => "ca"],
    "eo" => ["label" => "Esperanto", "countryCode" => "eu"],
    "es_PE" => ["label" => "Español de Perú", "countryCode" => "pe"],
    "es_CO" => ["label" => "Español de Colombia", "countryCode" => "co"],
    "es_ES" => ["label" => "Español", "countryCode" => "es"],
    "es_VE" => ["label" => "Español de Venezuela", "countryCode" => "ve"],
    "es_EC" => ["label" => "Español de Ecuador", "countryCode" => "ec"],
    "es_DO" => ["label" => "Español de República Dominicana", "countryCode" => "do"],
    "es_UY" => ["label" => "Español de Uruguay", "countryCode" => "uy"],
    "es_PR" => ["label" => "Español de Puerto Rico", "countryCode" => "pr"],
    "es_GT" => ["label" => "Español de Guatemala", "countryCode" => "gt"],
    "es_MX" => ["label" => "Español de México", "countryCode" => "mx"],
    "es_CR" => ["label" => "Español de Costa Rica", "countryCode" => "cr"],
    "es_CL" => ["label" => "Español de Chile", "countryCode" => "cl"],
    "es_AR" => ["label" => "Español de Argentina", "countryCode" => "ar"],
    "et" => ["label" => "Eesti", "countryCode" => "ee"],
    "eu" => ["label" => "Euskara", "countryCode" => "es"],
    "fa_AF" => ["label" => "فارسی (افغانستان)", "countryCode" => "af"],
    "fa_IR" => ["label" => "فارسی", "countryCode" => "ir"],
    "fi" => ["label" => "Suomi", "countryCode" => "fi"],
    "fr_CA" => ["label" => "Français du Canada", "countryCode" => "ca"],
    "fr_BE" => ["label" => "Français de Belgique", "countryCode" => "be"],
    "fr_FR" => ["label" => "Français", "countryCode" => "fr"],
    "fur" => ["label" => "Friulian", "countryCode" => "it"],
    "fy" => ["label" => "Frysk", "countryCode" => "nl"],
    "gd" => ["label" => "Gàidhlig", "countryCode" => "gb"],
    "gl_ES" => ["label" => "Galego", "countryCode" => "es"],
    "haz" => ["label" => "هزاره گی", "countryCode" => "af"],
    "he_IL" => ["label" => "עִבְרִית", "countryCode" => "il"],
    "hr" => ["label" => "Hrvatski", "countryCode" => "hr"],
    "hsb" => ["label" => "Hornjoserbšćina", "countryCode" => "de"],
    "hu_HU" => ["label" => "Magyar", "countryCode" => "hu"],
    "hy" => ["label" => "Հայերեն", "countryCode" => "am"],
    "id_ID" => ["label" => "Bahasa Indonesia", "countryCode" => "id"],
    "is_IS" => ["label" => "Íslenska", "countryCode" => "is"],
    "it_IT" => ["label" => "Italiano", "countryCode" => "it"],
    "ja" => ["label" => "日本語", "countryCode" => "jp"],
    "jv_ID" => ["label" => "Basa Jawa", "countryCode" => "id"],
    "ka_GE" => ["label" => "ქართული", "countryCode" => "ge"],
    "kab" => ["label" => "Taqbaylit", "countryCode" => "dz"],
    "kk" => ["label" => "Қазақ тілі", "countryCode" => "kz"],
    "km" => ["label" => "ភាសាខ្មែរ", "countryCode" => "kh"],
    "kn" => ["label" => "ಕನ್ನಡ", "countryCode" => "in"],
    "ko_KR" => ["label" => "한국어", "countryCode" => "kr"],
    "ckb" => ["label" => "كوردی‎", "countryCode" => "iq"],
    "kir" => ["label" => "Кыргызча", "countryCode" => "kg"],
    "lo" => ["label" => "ພາສາລາວ", "countryCode" => "la"],
    "lt_LT" => ["label" => "Lietuvių kalba", "countryCode" => "lt"],
    "lv" => ["label" => "Latviešu valoda", "countryCode" => "lv"],
    "mk_MK" => ["label" => "Македонски јазик", "countryCode" => "mk"],
    "ml_IN" => ["label" => "മലയാളം", "countryCode" => "in"],
    "mn" => ["label" => "Монгол", "countryCode" => "mn"],
    "mr" => ["label" => "मराठी", "countryCode" => "in"],
    "ms_MY" => ["label" => "Bahasa Melayu", "countryCode" => "my"],
    "my_MM" => ["label" => "ဗမာစာ", "countryCode" => "mm"],
    "nb_NO" => ["label" => "Norsk bokmål", "countryCode" => "no"],
    "ne_NP" => ["label" => "नेपाली", "countryCode" => "np"],
    "nl_BE" => ["label" => "Nederlands (België)", "countryCode" => "be"],
    "nl_NL" => ["label" => "Nederlands", "countryCode" => "nl"],
    "nn_NO" => ["label" => "Norsk nynorsk", "countryCode" => "no"],
    "oci" => ["label" => "Occitan", "countryCode" => "fr"],
    "pa_IN" => ["label" => "ਪੰਜਾਬੀ", "countryCode" => "in"],
    "pl_PL" => ["label" => "Polski", "countryCode" => "pl"],
    "ps" => ["label" => "پښتو", "countryCode" => "af"],
    "pt_PT" => ["label" => "Português", "countryCode" => "pt"],
    "pt_BR" => ["label" => "Português do Brasil", "countryCode" => "br"],
    "rhg" => ["label" => "Ruáinga", "countryCode" => "mm"],
    "ro_RO" => ["label" => "Română", "countryCode" => "ro"],
    "ru_RU" => ["label" => "Русский", "countryCode" => "ru"],
    "sah" => ["label" => "Сахалыы", "countryCode" => "ru"],
    "snd" => ["label" => "سنڌي", "countryCode" => "pk"],
    "si_LK" => ["label" => "සිංහල", "countryCode" => "lk"],
    "sk_SK" => ["label" => "Slovenčina", "countryCode" => "sk"],
    "skr" => ["label" => "سرائیکی", "countryCode" => "pk"],
    "sl_SI" => ["label" => "Slovenščina", "countryCode" => "si"],
    "sq" => ["label" => "Shqip", "countryCode" => "al"],
    "sr_RS" => ["label" => "Српски језик", "countryCode" => "rs"],
    "sv_SE" => ["label" => "Svenska", "countryCode" => "se"],
    "sw" => ["label" => "Kiswahili", "countryCode" => "tz"],
    "szl" => ["label" => "Ślōnskŏ gŏdka", "countryCode" => "pl"],
    "ta_IN" => ["label" => "தமிழ்", "countryCode" => "in"],
    "ta_LK" => ["label" => "தமிழ்", "countryCode" => "lk"],
    "te" => ["label" => "తెలుగు", "countryCode" => "in"],
    "th" => ["label" => "ไทย", "countryCode" => "th"],
    "tl" => ["label" => "Tagalog", "countryCode" => "ph"],
    "tr_TR" => ["label" => "Türkçe", "countryCode" => "tr"],
    "tt_RU" => ["label" => "Татар теле", "countryCode" => "ru"],
    "tah" => ["label" => "Reo Tahiti", "countryCode" => "pf"],
    "ug_CN" => ["label" => "ئۇيغۇرچە", "countryCode" => "cn"],
    "uk" => ["label" => "Українська", "countryCode" => "ua"],
    "ur" => ["label" => "اردو", "countryCode" => "pk"],
    "uz_UZ" => ["label" => "O‘zbekcha", "countryCode" => "uz"],
    "vi" => ["label" => "Tiếng Việt", "countryCode" => "vn"],
    "zh_TW" => ["label" => "繁體中文", "countryCode" => "tw"],
    "zh_CN" => ["label" => "简体中文", "countryCode" => "cn"],
    "zh_HK" => ["label" => "香港中文", "countryCode" => "hk"]
];
